### ISSUE TITLE
增加已有配置检测和修改功能

### ISSUE THREAD

**Issue by imbalaomao** [TinrLin/Script_installation#4]
问题描述：我在使用本脚本安装时，在已经安装过Tuic的情况下选择Tuic，仍然会进入安装步骤，但是我想修改对应配置的参数（如IP、域名等）

功能期望：除了直接去修改 `/usr/local/etc/sing-box/config.json` 以外能否在脚本里加入已有配置检测和修改的功能？

**Comment by TinrLin** [comment]
修改配置功能后期会添加，现在不支持

**Comment by imbalaomao** [comment]
好的，那我先通过修改文件的方式手动操作吧，期待功能添加
